version: 2

sources:
    - name: staging
      database: composed-facet-339115
      schema: trips_data_all

      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata_2019